CREATE TABLE despatch (
  serial_no INTEGER NOT NULL,
  date DATE NOT NULL,
  eng_to_whom_sent VARCHAR (255) NOT NULL,
  hi_to_whom_sent VARCHAR (255) NOT NULL,
  eng_place VARCHAR (255) NOT NULL,
  hi_place VARCHAR (255) NOT NULL,
  eng_subject VARCHAR (255) NOT NULL,
  hi_subject VARCHAR (255) NOT NULL,
  eng_sent_by VARCHAR (255) NOT NULL,
  hi_sent_by VARCHAR (255) NOT NULL,
  user_id INTEGER NOT NULL ,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  CONSTRAINT despatch_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (user_id)
);
