CREATE TABLE users (
  first_name VARCHAR (255) NOT NULL,
  last_name VARCHAR (255) NOT NULL,
  phone_no VARCHAR(15) NOT NULL,
  user_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY
);

ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);
